webapp/cont/views.py
from flask import Blueprint, Flask, render_template, request, flash, redirect, session, url_for

from webapp.utils import get_redirect_target
from webapp.events.models import Events
from webapp.breadcrumb import breadcrumb
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb


blueprint = Blueprint('cont', __name__, url_prefix='/')
default_breadcrumb_root(blueprint, '.')

@blueprint.route('/<city_id>')
def city_content(city_id):
    session.pop("city", None)
    session["city"] = city_id
    return redirect(get_redirect_target())

@blueprint.route('/about')
@register_breadcrumb(blueprint, '.about', 'О диск-гольфе')
def about_dg():
    title = "Узнай больше о диск-гольфе"
    return render_template('cont/about.html', page_title=title)

@blueprint.route('/mclass')
@register_breadcrumb(blueprint, '.mclass', 'Мастерклассы')
def mclass():
    title = "Попробуй поиграть в диск-гольф"
    return render_template('cont/mclass.html', page_title=title)

@blueprint.route('/where')
# @breadcrumb('Где поиграть')
@register_breadcrumb(blueprint, '.where', 'Где поиграть')
def where():
    title = "Где можно поиграть в диск-гольфа"
    return render_template('cont/where.html', page_title=title)

@blueprint.route('/beginner/<category_id>')
@register_breadcrumb(blueprint, '.beginner', 'Турниры начального уровня')
def beginner(category_id):
    title = "Попробуй посоревноваться"
    post_event = Events.query.filter(Events.category==category_id).limit(3).all()
    print(post_event)
    return render_template('cont/beginner.html', page_title=title, events=post_event)

@blueprint.route('/protour/<category_id>')
@register_breadcrumb(blueprint, '.protour', 'Профессиональные турниры')
def protour(category_id):
    title = "Зарубись с профессионалами диск-гольфа"
    post_event = Events.query.filter(Events.category==category_id).limit(3).all()
    print(post_event)
    return render_template('cont/protour.html', page_title=title, events=post_event)

@blueprint.route('/world/<category_id>')
@register_breadcrumb(blueprint, '.world', 'Международные турниры')
def world(category_id):
    title = "Стань здездой диск-гольфа"
    post_event = Events.query.filter(Events.category==category_id).limit(3).all()
    print(post_event)
    return render_template('cont/world.html', page_title=title, events=post_event)

@blueprint.route('/sponsorship')
@register_breadcrumb(blueprint, '.sponsorship', 'Спонсировать диск-гольф')
def sponsor():
    title = "Поддержи развитие диск-гольфа"
    return render_template('cont/sponsorship.html', page_title=title)

@blueprint.route('/tobuy')
@register_breadcrumb(blueprint, '.tobuy', 'Где купить')
def tobuy():
    title = "Где купить диски и корзины"
    return render_template('cont/tobuy.html', page_title=title)

@blueprint.route('/corp')
@register_breadcrumb(blueprint, '.corp', 'Корпоративным клиентам')
def corp():
    title = "Провести праздник диск-гольфа"
    return render_template('cont/corp.html', page_title=title)

webapp/user/views.py
from flask import Blueprint, Flask, render_template, flash, redirect, session, url_for
from flask_login import current_user, login_required, login_user, logout_user

from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.db import db
from webapp.utils import get_redirect_target


blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    page_title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=page_title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы вошли на сайт')
            return redirect(url_for('index'))
    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились!')
    return redirect(url_for('index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле {}: {}'.format(
                getatter(form, field).label.text,
                error
                ))
    flash('Пожалуйста, исправьте ошибки в форме')
    return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="/static/rdga.ico">
    <style>
      .page-holder {
        min-height: 100vh;
      }
      .bg-cover {
        background-size: cover !important;
        background: url(/static/bg1.png); /* bg2.jpg   bg1.png */
      }
      .box
      {
        position: relative;
        background: rgba(255, 255, 255, .2);
        box-shadow: 0 5px 15px rgba(0, 0, 0, .3);
      }
      .box-intens
      {
        position: relative;
        background: rgba(255, 255, 255, .8);
        box-shadow: 0 5px 15px rgba(0, 0, 0, .3);
      }
      .scale {
        transition: 0.5s; /* Время эффекта */
      }
      .scale:hover {
        transform: scale(1.6); /* Увеличиваем масштаб */
      }
      .position-relative {
        position: fixed;
      }
     </style>
    <title>{{ g.title }}</title>
  </head>
  
  <body>
    <div class="page-holder bg-cover">
      <div class="row">
        <br>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-7 my-auto">
            <h1 class="text-dark ml-3">ДИСК-ГОЛЬФ в РОССИИ</h1>
          </div>
          <div class="col-md-5">
            <div class="row">
            {% if current_user.is_authenticated %}
              <div class="col-md-5 mx-auto">
                <p class="my-2" style="font-size: 1.5vw;">Привет, {{ current_user.username }}</p>
              </div>
              <div class="col-md-2 mx-3 align-top">
                {% if current_user.is_admin %}
                  <a href="{{ url_for('admin.admin_index') }}" class="btn btn-light" role="button" aria-disabled="true">Админка</a>
                {% endif %}
              </div>
              <div class="col-md-2 mx-4 align-top">
                <a href="{{ url_for('user.logout') }}" class="btn btn-light" role="button" aria-disabled="true">Выйти</a>
                  <a class="nav-link" href="{{ url_for('user.logout') }}"></a>
              </div>
            {% else %}
              <div class="col-md-3 mx-auto align-top">
              </div>
              <div class="col-md-4 mx-auto align-top">
                <a href="{{ url_for('user.register') }}" class="btn btn-light" role="button" aria-disabled="true">Зарегистрироваться</a>
              </div>
              <div class="col-md-2 mx-4 align-top">
                <a href="{{ url_for('user.login') }}" class="btn btn-light" role="button" aria-disabled="true">Войти</a>
              </div>
            {% endif %}
          </div>
          </div>
        </div>
        <div class="sticky-top">
        {% include 'topmenu.html' %}
        </div>
        <nav aria-label="breadcrumb" class="ml-4 my-3">
          <p style="font-size: 1.8vw;">
            {% for breadcrumb in breadcrumbs %}
              <a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
              {{ '>' if not loop.last }}
            {% endfor %}
          </p>
        </nav>
        <main role="main">
          {% block content %}{% endblock %}
        </main>
      </div>
      <footer>
        <div class="container">
          <!--<p class="float-right">
            <a href="#">Наверх ↑</a>
          </p>-->
          <div class="row align-items-center">
            <div class="col-sm-4 offset-md-1 py-4">
              <h3 class="text-black">Контакты</h3>
              <ul class="list-unstyled">
                {% if session['city'] == 'no' %}
                  <li><a href="https://www.instagram.com/discgolf_spb/" class="text-secodary"><h5>Инстаграм: discgolf_russia</h5></a></li>
                  <li><a href="https://vk.com/discgolfspb" class="text-secodary"><h5>ВК: rdga</h5></a></li>
                  <li><a href="#" class="text-secodary"><h5>Email: example@gmail.com</h5></a></li>
                {% elif session['city'] == 'Msc' %}
                  <li><a href="https://www.instagram.com/discgolf_spb/" class="text-secodary"><h5>Инстаграм: discgolf.msk</h5></a></li>
                  <li><a href="https://vk.com/discgolfspb" class="text-secodary"><h5>ВК: discgolfmsk</h5></a></li>
                  <li><a href="#" class="text-secodary"><h5>Email: discgolfmsk@gmail.com</h5></a></li>
                {% elif session['city'] == 'SPb' %}
                  <li><a href="https://www.instagram.com/discgolf_spb/" class="text-secodary"><h5>Инстаграм: discgolf_spb</h5></a></li>
                  <li><a href="https://vk.com/discgolfspb" class="text-secodary"><h5>ВК: discgolfspb</h5></a></li>
                  <li><a href="#" class="text-secodary"><h5>Email: discgolfspb@gmail.com</h5></a></li>
                {% elif session['city'] == 'Ekb' %}
                <li><a href="https://www.instagram.com/discgolf_ekb/" class="text-secodary"><h5>Инстаграм: discgolf_ekb</h5></a></li>
                <li><a href="https://vk.com/discgolf_ekb" class="text-secodary"><h5>ВК: discgolfekb</h5></a></li>
                <li><a href="#" class="text-secodary"><h5>Email: ffds.info@ya.ru</h5></a></li>
                {% endif %}
              </ul>
            </div>
            <div class="col-4 offset-md-1">
              <img src="/static/rdga.png" class="float-right aligin-center" alt="logo" width="120" height="120">
            </div>
          </div>
        </div>
      <div class="row">
        <br>
      </div>
      </footer>
      
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>document.cookie = "ex=1;";
        if (!document.cookie)
        {
          alert("Этот сайт требует включенных cookies для своей корректной работы")
        }</script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}

{% block content %}
        <div class="album py-5 box">
          <div class="container">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
              <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                  {{ message }}<br>
                {% endfor %}
              </div>
              {% endif %}
            {% endwith %}
            <div class="text-dark">
              <div class="row">
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.about_dg') }}">
                      <img src="/static/about.jpg" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                      <div class="ml-3">
                        <p><h4>Узнать о диск-гольфе</h4></p>
                      </div>
                    </div>
                </div>
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.mclass') }}">
                    <img src="/static/mclass.JPG" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                    <div class="ml-3">
                      <p><h4>Пройти мастер-класс</h4></p>
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.where') }}">
                    <img src="/static/where.jpg" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                    <div class="ml-3">
                      <p><h4>Играть самому с друзьями</h4></p>
                    </div>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.beginner', category_id='Beginner') }}">
                    <img src="/static/beginner.jpg" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                    <div class="ml-3">
                      <p><h4>Участвовать в турнире &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4></p>
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.protour', category_id='ProTour') }}">
                    <img src="/static/protour.jpg" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                    <div class="mx-3">
                      <p><h4>Соревноваться с профессионалами</h4></p>
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow bg-white">
                    <a href="{{ url_for('cont.world', category_id='World') }}">
                    <img src="/static/world.jpg" class="rounded mx-auto d-block" width=100% height=100% alt="альтернативный текст"></a>
                    <div class="mx-3">
                      <p><h4>Международные соревнования</h4></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock %}    

webapp/templates/steps.html
<br>
<div class="container">
  <div class="row text-center">
    <div class="col-md-2 scale">
      <a class="nav-link" href="{{ url_for('cont.about_dg') }}">
        <img src="/static/BC1.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
    <div class="col-md-2 scale text-center">
      <a class="nav-link" href="{{ url_for('cont.mclass') }}">
        <img src="/static/BC2.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
    <div class="col-md-2 scale text-center">
      <a class="nav-link" href="{{ url_for('cont.where') }}">
        <img src="/static/BC3.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
    <div class="col-md-2 scale text-center">
      <a class="nav-link" href="{{ url_for('cont.beginner', category_id='Beginner') }}">
        <img src="/static/BC4.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
    <div class="col-md-2 scale text-center">
      <a class="nav-link" href="{{ url_for('cont.protour', category_id='ProTour') }}">
        <img src="/static/BC5.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
    <div class="col-md-2 scale text-center">
      <a class="nav-link" href="{{ url_for('cont.protour', category_id='ProTour') }}">
        <img src="/static/BC6.png" alt="logo" class="rounded" width=100% height=100%>
      </a>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-2">
      <h5 class="text-dark text-center">Что такое<br>диск-гольф?</h5>
    </div>
    <div class="col-md-2">
      <h5 class="text-dark text-center">Когда<br>мастеркласс?</h5>
    </div>
    <div class="col-md-2">
      <h5 class="text-dark text-center">Играть самому<br>с друзьями!</h5>
    </div>
    <div class="col-md-2">
      <h5 class="text-dark text-center">Участвуй<br>в турнире!</h5>
    </div>
    <div class="col-md-2">
      <h5 class="text-dark text-center">Соревнуйся<br>с про!</h5>
    </div>
    <div class="col-md-2">
      <h5 class="text-dark text-center">Играй за<br>границей!</h5>
    </div>
  </div>
</div>

webapp/templates/topmenu.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light box-intens">
  <a class="navbar-brand ml-3" href="/"><h4>Главная</h4></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-2">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('cont.tobuy') }}"><h4>Магазин</h4></a>
      </li>
      <li class="nav-item ml-2">
        <a class="nav-link" href="{{ url_for('cont.corp') }}"><h4>Компаниям</h4></a>
      </li>
      <li class="nav-item ml-2">
        <a class="nav-link" href="{{ url_for('cont.sponsor') }}"><h4>Спонсировать</h4></a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a style="font-size: 1.6vw;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if session['city'] == 'no' %}
            Выбирите город
          {% elif session['city'] == 'Msc' %}
            Москва
          {% elif session['city'] == 'SPb' %}
            Санкт-Петербург
          {% elif session['city'] == 'Ekb' %}
            Екатеринбург
          {% elif session['city'] == 'NN' %}
            Нижний Новгород
          {% elif session['city'] == 'Blg' %}
            Белгород
          {% elif session['city'] == 'Other' %}
            Выбирите город
          {% endif %}
        </a>
        <div class="nav-item dropdown"> <!--<button class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Выбирите город</button>-->
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='Msc')}}">Москва</a>
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='SPb')}}">Санкт_Петербург</a>
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='Ekb')}}">Екатеринбург</a>
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='NN')}}">Нижний Новгород</a>
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='Blg')}}">Белгород</a>
            <a class="dropdown-item" href="{{ url_for('cont.city_content', city_id='Other')}}">Другой город</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Построить парк</a>
          </div>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!--
<nav aria-label="breadcrumb" class="ml-4">
  <p>
    {% for breadcrumb in breadcrumbs %}
      <a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
      {{ '/' if not loop.last }}
    {% endfor %}
  </p>
</nav>
-->